platform :ios, '9.0'

target 'TheatreBud' do
  use_frameworks!

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase'

  target 'TheatreBudUITests' do
    inherit! :search_paths
  end

end
